- hosts: localhost
  vars:
    admin_url: "https://ipt-admin.3scale.net"
    access_token: "access_token=fc26f4bdf71813e5136b5f99d7bc2c0f775fe0fa9b9b3dc6df117249b6196604"
    private_url: "https://redhatdemo3-api-backend-test.192.168.64.2.nip.io:443"
    public_url: "https://apicast-api-gateway-test.192.168.64.2.nip.io:443"
  tasks:

  - name: create service
    uri:
      url: "{{ admin_url }}/admin/api/services.json"
      method: POST
      headers:
        Content-Type: application/x-www-form-urlencoded
      body: "{{ access_token }}&name=DummyAPI&system_name=dummyapi"
      return_content: yes
      status_code: 201
      validate_certs: no
    register: service_result1
  - debug: msg="{{ service_result1.json }}"
  - set_fact: service_id="{{ service_result1.json.service.id }}"
  - debug: msg="Service ID = {{ service_id }}"

